### ISSUE TITLE
Unable to build new version

### ISSUE THREAD

**Issue by chrisgiordano720** [jason-tratta/ProgressScreen#5]
Hi there,

I'm working getting ProgressScreen customized for our DEP deployment, however I'm unable to build a signed version of the app because of this error after updating it to the latest stable version of 
Swift 3 and Xcode 8.3.3.

<img width="1090" alt="screen shot 2017-06-12 at 2 56 54 pm" src="https://user-images.githubusercontent.com/26261569/27057085-7013fc04-4f7f-11e7-9e40-10756b97eeac.png">

I have no clue about app development so I'm not even sure how to go about fixing that error.
Any help would be great!
Thanks!
Chris

**Comment by jason-tratta** [comment]
Hi Chris, 

Is that an older version of the codebase?  That looks like it could be from before the Swift language update. If you already have a lot of code baked in, try changing that line to"

 var logLine: NSString?

Otherwise, try most recent version.  That is compiling for me in Xcode version 8.3.3.

**Comment by chrisgiordano720** [comment]
Hi Jason,

Sorry for the false alarm.  I thought I was using the most recent one.
There's like two or three different versions out there between Github and
Github.io :)  I download each one and found the one on your main page of
Github compile correctly!

Thanks for assistance!
Have a good one!
Chris
